#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Import/Import.csproj", "Import/"]
COPY ["Import.Logic/Import.Logic.csproj", "Import.Logic/"]
COPY ["General/General.csproj", "General/"]
RUN dotnet restore "Import/Import.csproj"
COPY . .
WORKDIR "/src/Import"
RUN dotnet build "Import.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Import.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Import.dll"]